### PR TITLE
Wilke/config

### PR DESCRIPTION
**Pull request by wilke**
Introducing config creation from script and template. The user config should not be part of the repository.

### CODE REVIEW

**Review by AlexandrNP — COMMENTED** [review]
I am not sure about changing CANDLE_DATA_DIR to IMPROVE_DATA_DIR. Candle framework would look specifically for CANDLE_DATA_DIR environmental variable

**Comment by wilke** [comment]
> I am not sure about changing CANDLE_DATA_DIR to IMPROVE_DATA_DIR. Candle framework would look specifically for CANDLE_DATA_DIR environmental variable

CANDLE_DATA_DIR will be set in the interface scripts or bootstrap. IDD or IMPROVE_DATA_DIR is the name used in the testing suite historically to clearly separate the outside environment from the container environment.

**Comment by wilke** [comment]
@AlexandrNP Apart from the naming convention do you agree with the changes and is it working for you?

**Comment by AlexandrNP** [comment]
Yes, thanks for the clarification.
When discussing separating external and internal variables, do you mean the path within the container and outside of it?
Because CANDLE_DATA_DIR should point to the data within the container.
The container can mount an external folder, but right now, I do not see how the CANDLE framework would know the correct environment.

**Review by AlexandrNP — APPROVED** [review]

**Pull request merged**
